src/Entity/EgoGame.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EgoGameRepository")
 */
class EgoGame
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $game_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $game_id;

    /**
     * Plusieurs offres sont liées à une lineUp
     * @ORM\ManyToOne(targetEntity="User", inversedBy="egoGames")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $ownNote;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="PubNote", mappedBy="egoGame", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $pubNotes;

    public function __construct()
    {
        $this->pubNotes = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGameName(): ?string
    {
        return $this->game_name;
    }

    public function setGameName(string $game_name): self
    {
        $this->game_name = $game_name;

        return $this;
    }

    public function getGameId(): ?int
    {
        return $this->game_id;
    }

    public function setGameId(int $game_id): self
    {
        $this->game_id = $game_id;

        return $this;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getOwnNote(): ?int
    {
        return $this->ownNote;
    }

    public function setOwnNote(int $ownNote): self
    {
        $this->ownNote = $ownNote;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPubNotes()
    {
        return $this->pubNotes;
    }

    public function setPubNotes($pubNotes): self
    {
        $this->pubNotes = $pubNotes;

        return $this;
    }

    public function addPubNote(PubNote $pubNote): self
    {
        if (!$this->pubNotes->contains($pubNote)) {
            $this->pubNotes[] = $pubNote;
            $pubNote->setEgoGame($this);
        }

        return $this;
    }

    public function removePubNote(PubNote $pubNote): self
    {
        if ($this->pubNotes->contains($pubNote)) {
            $this->pubNotes->removeElement($pubNote);
            // set the owning side to null (unless already changed)
            if ($pubNote->getEgoGame() === $this) {
                $pubNote->setEgoGame(null);
            }
        }

        return $this;
    }
}

src/Form/LineupType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LineupType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('system_name', HiddenType::class, [
            'required' => true
        ])
            ->add('game_name', TextType::class, [
                'required' => true,
                'attr' => ['class' => 'form-control']
            ])
            ->add('game_id', HiddenType::class, [
                'required' => true
            ])
            ->add('system_id', HiddenType::class, [
                'required' => true
            ])
            ->add('image', HiddenType::class)
        ;
    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Lineup'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_lineup';
    }


}

src/Controller/LineupController.php
<?php

namespace App\Controller;

use App\Entity\Lineup;
use App\Entity\Notification;
use App\Entity\Team;
use App\Entity\User;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Offer;
/**
 * Lineup controller.
 *
 * @Route("lineup")
 */
class LineupController extends Controller
{
    /**
     * Lists all lineup entities.
     *
     * @Route("/", name="lineup_index", methods={"GET"})
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $lineups = $em->getRepository('AppBundle:Lineup')->findAll();

        return $this->render('lineup/index.html.twig', array(
            'lineups' => $lineups,
        ));
    }

    /**
     * Creates a new lineup entity.
     *
     * @Route("/new", name="lineup_new", methods={"GET", "POST"})     *
     * @return Response
     */
    public function newAction(Request $request):Response
    {
        $user = $this->getUser();
        $team = $user->getTeam();
        $lineup = new Lineup();
        $lineup->setTeam($team);
        $form = $this->createForm('App\Form\LineupType', $lineup);
        $form->handleRequest($request);
        $data = $form->getData();
        if ($form->isSubmitted() && ($data->getGameId() == null || $data->getSystemId() == null || $data->getGameName() == null || $data->getSystemName() == null)){
            $this->addFlash('warning', 'Vous devez remplir entièrement les champs !');
            return $this->redirectToRoute('lineup_new');
        }
        if ($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();
            $lineup->setGameId($data->getGameId());
            $lineup->setSystemId($data->getSystemId());
            $lineup->setGameName($data->getGameName());
            $lineup->setSystemName($data->getSystemName());
            $lineup->setImage($data->getImage());

            $em = $this->getDoctrine()->getManager();
            $em->persist($lineup);
            $em->flush();

            return $this->redirectToRoute('display_team', array('ID' => $team->getId()));
        }

        return $this->render('lineup/new.html.twig', array(
            'lineup' => $lineup,
            'team' => $team,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a lineup entity.
     *
     * @Route("/{ID}", name="lineup_show", methods={"GET", "POST"})
     */
    public function showAction(int $ID, Request $request, ManagerRegistry $doctrine, PaginatorInterface $paginator, EntityManagerInterface $em)
    {
        $lineup = $doctrine->getRepository(Lineup::class)->findOneBy(['id' => $ID]);
        $deleteForm = $this->createDeleteForm($lineup);

        $offer = new Offer();
        $form = $this->createForm('App\Form\OfferType', $offer);
        $form->handleRequest($request);

        //chercher user

        $userRepository = $em->getRepository(User::class);
        if($request->query->get('query')){
            $pagination = $paginator->paginate(
                $userRepository->findByPseudo($request->query->get('query')), // La query que l'on veut paginer
                $request->query->getInt('page', 1), // On récupère le numéro de la page et on le défini à 1 par défaut
                8 // Nombre d'éléments affiché par page
            );
        }else {

            $pagination = $paginator->paginate(
                $userRepository->findNotTeamed(), // La query que l'on veut paginer
                $request->query->getInt('page', 1), // On récupère le numéro de la page et on le défini à 1 par défaut
                8 // Nombre d'éléments affiché par page
            );
        }

        if ($form->isSubmitted() && $form->isValid()) {

            $offer->setLineUp($lineup);

            $em = $this->getDoctrine()->getManager();
            $em->persist($offer);
            $em->flush();
            $this->addFlash('success', 'Votre offre de recrutement est en ligne.');
            return $this->redirectToRoute('lineup_show', array('ID' => $lineup->getId()));
        }

        return $this->render('lineup/show.html.twig', array(
            'lineup' => $lineup,
            'delete_form' => $deleteForm->createView(),
            'pagination' => $pagination,
            'form' => $form->createView()
        ));
    }

    /**
     *
     * @Route("/{ID}/invit/{ID_lineup}", name="send_invit", methods={"GET"})
     */
    public function sendInvit(int $ID, int $ID_lineup, EntityManagerInterface $em, ManagerRegistry $doctrine):Response
    {
        $lineup = $doctrine->getRepository(Lineup::class)->findOneBy(['id' => $ID_lineup]);
        $user_emet = $this->getUser();
        $user_recep = $doctrine->getRepository(User::class)->findOneBy(['id' => $ID]);




        $notification = new Notification();
        $notification->setEmett($user_emet);
        $notification->setRecep($user_recep);
        $notification->setContent(
            $user_emet->getPseudo().$user_emet->getProfileName().
            " vous a invité à rejoindre la line-up ".
            $lineup->getGameName().
            " de la team ".
            $lineup->getTeam()->getName()
        );
        $notification->setType("invitation");
        $notification->setLineup($lineup);

        $em = $this->getDoctrine()->getManager();
        $em->persist($notification);
        $em->flush();
        $this->addFlash('success', 'Votre invitation a bien été envoyée.');
        return $this->redirectToRoute('lineup_show', ['lineup' => $lineup, 'ID' => $lineup->getId()]);
    }

    /**
     *
     * @Route("/{ID}/accept_invit/{ID_invit}/{ID_lineup}", name="accept_invit", methods={"GET"})
     */
    public function acceptInvit(int $ID, int $ID_lineup, int $ID_invit, EntityManagerInterface $em, ManagerRegistry $doctrine):Response
    {
        $lineup = $doctrine->getRepository(Lineup::class)->findOneBy(['id' => $ID_lineup]);
        $user_emet = $this->getUser();
        $user_recep = $doctrine->getRepository(User::class)->findOneBy(['id' => $ID]);
        $notif_invit = $doctrine->getRepository(Notification::class)->findOneBy(['id' => $ID_invit]);
        //on verifie que l'user n'ait pas deja de team
        $users_non_teamed = $doctrine->getRepository(User::class)->findNotTeamed()->getResult();

        if(in_array($user_emet, $users_non_teamed) && !empty($users_non_teamed)){


            //on crée la notification d'acceptation
            $notification = new Notification();
            $notification->setEmett($user_emet);
            $notification->setRecep($user_recep);
            $notification->setContent(
                $user_emet->getPseudo().$user_emet->getProfileName().
                " a accepté votre invitation à rejoindre la line-up ".
                $lineup->getGameName().
                " de la team ".
                $lineup->getTeam()->getName()
            );
            $notification->setType("accept_invitation");

            //On crée le flashmessage qui confirme l'ajout a la line up
            $flashmessage = "Bienvenue dans la line-up ".
                $lineup->getGameName().
                " de la team ".
                $lineup->getTeam()->getName();

            //On set la lineup de l'user, on passe la notif en status 2 et on flush les entités
            $user_emet->setLineUp($lineup);
            $notif_invit->setStatus(2);
            $em = $this->getDoctrine()->getManager();
            $em->persist($notif_invit);
            $em->persist($notification);
            $em->persist($user_emet);
            $em->flush();

            $this->addFlash('success', $flashmessage);
            return $this->redirectToRoute('lineup_show', ['lineup' => $lineup, 'ID' => $lineup->getId()]);
        }

            $this->addFlash('warning', 'Vous faites déjà parti d\'une team, veuillez la quitter avant d\'en rejoindre une autre.');
            return $this->redirectToRoute('usernotification');
    }

    /**
     *
     * @Route("/{ID}/refuse_invit/{ID_invit}/{ID_lineup}", name="refuse_invit", methods={"GET"})
     */
    public function refuseInvit(int $ID, int $ID_lineup, int $ID_invit, EntityManagerInterface $em, ManagerRegistry $doctrine):Response
    {
        $lineup = $doctrine->getRepository(Lineup::class)->findOneBy(['id' => $ID_lineup]);
        $user_emet = $this->getUser();
        $user_recep = $doctrine->getRepository(User::class)->findOneBy(['id' => $ID]);
        $notif_invit = $doctrine->getRepository(Notification::class)->findOneBy(['id' => $ID_invit]);

            //on crée la notification d'acceptation
            $notification = new Notification();
            $notification->setEmett($user_emet);
            $notification->setRecep($user_recep);
            $notification->setContent(
                $user_emet->getPseudo().$user_emet->getProfileName().
                " a décliné votre invitation à rejoindre la line-up ".
                $lineup->getGameName().
                " de la team ".
                $lineup->getTeam()->getName()
            );
            $notification->setType("refuse_invitation");

            //On crée le flashmessage qui confirme l'ajout a la line up
            $flashmessage = "Invitation refusée.";

            //On set la lineup de l'user, on passe la notif en status 2 et on flush les entités
            $notif_invit->setStatus(2);
            $em = $this->getDoctrine()->getManager();
            $em->persist($notif_invit);
            $em->persist($notification);
            $em->flush();

            $this->addFlash('success', $flashmessage);
            return $this->redirectToRoute('usernotification');


    }

    /**
     * Displays a form to edit an existing lineup entity.

templates/lineup/_member.html.twig
<div class="post" style="padding: 28px 28px;font-size:12px;">

    {{ member.pseudo }}

</div>

templates/lineup/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Lineup edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}

    <ul>
        <li>
            <a href="{{ path('lineup_index') }}">Back to the list</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}

templates/lineup/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Lineups list</h1>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lineup in lineups %}
            <tr>
                <td><a href="{{ path('lineup_show', { 'id': lineup.id }) }}">{{ lineup.id }}</a></td>
                <td>
                    <ul>
                        <li>
                            <a href="{{ path('lineup_show', { 'id': lineup.id }) }}">show</a>
                        </li>
                        <li>
                            <a href="{{ path('lineup_edit', { 'id': lineup.id }) }}">edit</a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('lineup_new') }}">Create a new lineup</a>
        </li>
    </ul>
{% endblock %}

templates/lineup/new.html.twig
{% extends "/layout.html.twig" %}
{% block title %}TeamUP - Ajouter une nouvelle line-up{% endblock title %}


{% block page %}
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{{path('dashboard')}}">Accueil</a></li>
            <li><a href="{{path('display_team', { 'ID' : team.id })}}">{{ team.name }}</a></li>
            <li class="active">Gestion des line-ups</li>
        </ol>
    </div>
{% endblock page %}

{% block content %}

    <div class="content">
        <div class="navUser">
            <a href="{{path('admin_team', { 'ID' : team.id })}}" {% if app.request.get('_route') == 'admin_team' %}class="active"{% endif %}>Informations</a>
            <a href="{{path('lineup_new')}}" {% if app.request.get('_route') == 'lineup_new' %}class="active"{% endif %}>Line-ups</a>

        </div>
        <h2>Ajouter une nouvelle line-up</h2>
        <div class="row">
            <div class="col-md-1">

                        <img id="image" style="border-radius: 3px;" src="http://images.igdb.com/igdb/image/upload/t_thumb/co1jmh.jpg" alt=""
                             width="70px" height="auto">
            </div>
                        {{ form_start(form) }}
            <div class="col-md-11">            
                                {{ form_label(form.game_name, 'Effectuez une recherche du jeu vidéo' ) }}
                                {{ form_widget(form.game_name) }}
                                <i id="recherche" style="position: absolute;top: 41px;font-size: 18px;right: 37px;" class="fas fa-search"></i>
            </div>
        </div>
                        
                            
                        
                
                    <div class="row">
                        <div class="col-md-6">
                            <label for="id_game" class="required">Sélection du jeu</label>
                            <select name="id_game" id="id_game" class="result form-control" disabled>
                                <option value="" selected>Lancez une recherche puis sélectionnez un jeu ici ...</option>
                            </select>
                            </div>
                        <div class="col-md-6">
                            {{ form_label(form.system_id, 'Plateforme' ) }}
                            <select name="id_system" class="result_system form-control" disabled>
                                <option value="null" selected>Sélectionnez d'abord un jeu puis sélectionnez une plateforme ici ...</option>
                            </select>
                        </div>
                            {{ form_widget(form.system_id) }}                            
                            {{ form_widget(form.game_id) }}
                                <div class="col-sm-12">
                                    <input type="submit" name="submit" value="Valider" class="btn btn_orange center_block">
                                </div>
                        
                    </div>
                    {{ form_end(form) }}
               
                {#<div class="col-sm-1">#}
                {#<input type="button" value="Rechercher" id="recherche" class="btn btn-success">#}
                {#</div>#}
            </div>


    </div>










        
            
     

{% endblock content %}


{% block javascripts %}
    {{ parent() }}
    <script type='text/javascript'>
        $( document ).ready(function() {
            $("#appbundle_lineup_game_name").on( "keyup", function() {
                if($(this).val()){
                    $('.result').attr('disabled', true);
                    $('.result_system').attr('disabled', true);
                }
            });
            $( "#recherche" ).on( "click", function() {
                $(".result").empty();
                $('.result').attr('disabled', false);
                $(".result").append("<option value='null' selected>Lancez une recherche puis sélectionnez un jeu ici ...</option>");
                $.ajax({
                    url: "/api/games/"+$("#appbundle_lineup_game_name").val(),
                    context: document.body
                }).done(function( msg ) {
                    console.log(msg);
                    for (var result in msg) {
                        if (msg[result]['platforms'] != undefined) {
                            $(".result").append("<option data-name='" + msg[result]['name'] + "' value='" + msg[result]['id'] + "' data-platforms='" + msg[result]['platforms'] + "' data-coverid='" + msg[result]['cover'] + "'  >" + msg[result]['name'] + "</option>");
                        }
                    }
                });
            });
            $("select[name='id_game']").on("change", function () {
                $('#appbundle_lineup_game_id').val(this.value);
                $('#appbundle_lineup_game_name').val($(this).find(':selected').attr('data-name'));

                //console.log($(this).find(':selected').attr('data-name'));
                //console.log ($(this).find(':selected').attr('data-platforms'));
                $('#appbundle_lineup_system_id').val($(this).find(':selected').attr('data-platforms'));

                let systems = $(this).find(':selected').attr('data-platforms').split(",");
                $(".result_system").empty();
                $('.result_system').attr('disabled', false);
                $("select[name='id_system']").append("<option value='null' selected>Sélectionnez d'abord un jeu puis sélectionnez une plateforme ici ...</option>");
                for (var system in systems) {
                    if (systems[system] != "undefined") {
                        $.ajax({
                            url: "/api/system/" + systems[system],
                            context: document.body
                        }).done(function (msg) {
                            $("select[name='id_system']").append("<option value='"+msg[0]['name']+"' data-name='"+msg[0]['name']+"' data-id='"+msg[0]['id']+"'>"+msg[0]['name']+"</option>");
                            $('#appbundle_lineup_system').val(systems[system]);

                            //Chargement du cover
                            console.log($(this).find(':selected').attr('data-coverid'));
                            $.ajax({
                                url: "/api/cover/"+$(this).find(':selected').attr('data-coverid'),
                            }).done(function( msg ) {
                                $('#appbundle_lineup_image').val("http:"+msg[0]['url']);
                                $('#image').attr('src', 'http:'+msg[0]['url']);
                            });
                            //Fin de chargement du cover
                        });
                    } else {
                        $(".result_system").append("<option value=''>Non renseigné</option>");
                    }
                }
                $('.result_system').css("display","block");

            });
            $("select[name='id_system']").on("click", function () {
                $('#appbundle_lineup_system_id').val($(this).find(':selected').attr('data-id'));
                $('#appbundle_lineup_system_name').val($(this).find(':selected').attr('data-name'));
            })
        });


    </script>
{% endblock javascripts %}

templates/lineup/show.html.twig
{% extends "/layout.html.twig" %}
{% block title %}TeamUP - Line-up {{ lineup.gameName }}{% endblock title %}
{% block page %}
    <div class="team_banner" style="{% if lineup.team.banner != null %}background-image:url({{ asset('uploads/team_banner/') }}{{ lineup.team.banner }}){% else %}background:grey{% endif %}"></div>
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{{path('dashboard')}}">Accueil</a></li>
            <li><a href="{{ path('display_team', { 'ID' : lineup.team.id }) }}">{{ lineup.team.name }}</a></li>
            <li class="active">Line-up {{ lineup.gameName }}</li>
        </ol>
    </div>
{% endblock page %}


{% block content %}



    <div class="content" style="padding:13px">
        <div class="col-md-4">
            <div class="team_logo" style="{% if lineup.team.logo != null %}background-image:url({{ asset('uploads/team_logo/') }}{{ lineup.team.logo }}){% else %}background:grey{% endif %};"></div>

        </div>
        <div class="col-md-4">
            <h1>Line-up {{ lineup.gameName }}</h1>
            <img id="image" style="border-radius: 3px;margin: 0 auto;display: block;" src="{{ lineup.image }}" alt=""  width="70px" height="auto">
        </div>
        <div class="col-md-4" style="">
        <span class="grey_text" style="text-align: right;display:block;">Responsable : <a class="linkhover" style="font-weight: bold" href="{{ path('user_show', { 'id' : lineup.team.owner.id }) }}">{{  lineup.team.owner.pseudo }}{{  lineup.team.owner.profileName }}</a></span>
        <div style="display:none;">
        {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
                {{ form_end(delete_form) }}
<a href="{{ path('lineup_edit', { 'ID': lineup.id }) }}">Edit</a>
</div>



            </div>
            <div style="clear:both"></div>

    </div>

    <div class="content" style="padding:0px 0px 20px">
        <h2>Membres</h2>
        {% for user in lineup.members %}

          {% include 'User/_user.html.twig' %}


    {% else %}
    <div class="padding_int">
    <i class="fas fa-user-alt-slash"></i>
      <span style="" class="grey_text">Il n'y a pas encore de membre dans cette lineup.</span>
    </div>
    {% endfor %}
<div class="clearboth"></div>
    </div>
{% if lineup.team.owner == app.user %}
    <div class="content" style="padding:0px">
        <h2>Inviter de nouveaux membres</h2>
    <div style="padding:20px">
    <form style="position: relative;" action="" method="GET">
      <input class="form-control" placeholder="Rechercher un utilisateur par son pseudo" name="query" type="text">
      <input id="searchUser" style="display:none;" type="submit"/><i id="recherche" style="position: absolute;top: 17px;font-size: 18px;right: 24px;" class="fas fa-search"></i>
    </form>


  {% for user in pagination %}
<div class="col-md-3">
<div class="encart" style="margin-bottom: 20px;">
<a class="linkhover" href="{{ path('user_show', { 'id' : user.id }) }}">
    <div style="width:76px;height:76px;border-radius:50%;background-image: url('{% if user.steamId == 0 %}{{ asset('uploads/profil_pic/') }}{{ user.profilPic }}{% else %}{{ user.avatar }}{% endif %}');background-size: cover;margin:0 auto;"></div>
    <span style="text-align: center;display: block;" class="grey_text">{% if user.steamId == 0 %}{{ user.pseudo }}{% else %}{{ user.profileName}}{% endif %}</span>
    </a>
    <a class="btn_grey btn" style="padding-top: 6px;padding-bottom: 6px;text-transform: inherit;white-space: normal;" href="{{ path('send_invit', { 'ID' : user.id, 'ID_lineup' : lineup.id}) }}">Envoyer une invitation</a>
</div>
</div>



    {% endfor %}
    <div style="clear:both"></div>
    <div class="navigation center_block">
    {{ knp_pagination_render(pagination) }}
  </div>
  </div>
 </div>
 <div class="col-md-6" style="padding-left:0px">
     <div class="content" style="padding:0px">
     <h2>Créer une offre de recrutement</h2>
         <div style="padding:20px;">
         {{ form_start(form) }}
         {{ form_row(form.title) }}
         {{ form_row(form.text) }}
         <input type="submit" class="btn center_block btn_orange" value="Créer" />
         {{ form_end(form) }}

        </div>
</div>
</div>
<div class="col-md-6" style="padding-right:0px">
     <div class="content" style="padding:0px">
     <h2>Offres de recrutement</h2>
         <div style="padding:20px;">
         {% if lineup.offers is not empty %}
    <table width="100%">
    <tr >
    <th>Intitulé du poste</th>
    <th>Candidatures</th>
    <th>Action</th>
    </tr>
            {% for offer in lineup.offers %}
<tr style="    height: 80px;">
<td>{{ offer.title }}</td>
     <td style="text-align: center">{{ offer.applications|length }}</td>
     <td style="text-align: center"><a href="{{ path('offer_show', { 'id' : offer.id }) }}" class="btn btn_grey lil_btn center_block">Consulter</a></td>
</tr>




    {% endfor %}
    </table>
    {% else %}
    <div class="">
      <span style="" class="grey_text">Aucune offre de recrutement en cours pour cette line-up.</span>
    </div>
             {% endif %}
        </div>

    </div>
</div>
{% endif %}
{% endblock content %}


{% block javascripts %}
    {{ parent() }}
    <script>

        let recherche = jQuery("#recherche");
        recherche.click(function() {

            $("#searchUser").click();
        });





    </script>


{% endblock javascripts %}

templates/lineup/test.html.twig
<div class="post" style="padding: 28px 28px;font-size:12px;">
    {% block search %}
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    {% endblock %}

</div>